---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: pulp-single-container
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: pulp-single-container
  spec:
    envName: env-pulp-single-container
  deployments:
  - name: pulp-single-container
    podSpec:
      image: quay.io/pulp/pulp
      webServices:
        public:
          enabled: true
        metrics:
          enabled: true
  kafkaTopics:
    - replicas: 3
      partitions: 64
      topicName: topicOne
  volumeMounts:
    - name: settings
      mountPath: /etc/pulp/settings.py
      subPath: settings.py
  volumes:
    - name: settings
      configMap:
        name: settings

apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
data:
  settings.py: |
    CONTENT_ORIGIN='http://changeme:8080'
    ANSIBLE_API_HOSTNAME='http://changeme:8080'
    ANSIBLE_CONTENT_HOSTNAME='http://changeme:8080/pulp/content'
    TOKEN_AUTH_DISABLED=True
